### ISSUE TITLE
Using Alerting with AwReporting

### ISSUE THREAD

**Issue by Timmeh74** [googleads/adwords-alerting#3]
Hi!

Is there any documentation available on how this tool needs to be set up to make it request data from a local database instead of querying the API? In the Hamburg workshop I was told that it can be used together with AwReporting, which would be pretty neat.

Regards,
Tim

**Comment by chenzhuo914** [comment]
Hi Tim, actually you just need to use JDBC to query local database that AwReporting persists report data into.

We have a sample implementation [SqlDbReportDownloader](https://github.com/googleads/adwords-alerting/blob/master/src/main/java/com/google/api/ads/adwords/awalerting/sampleimpl/downloader/SqlDbReportDownloader.java), which you can refer as a starting point. Note that it simply queries the database, so you need to make sure that AwReporting should be scheduled to run and download report data beforehand. Feel free to modify the code (or make another custom implementation) to meet your specific requirements!
